name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Formats

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, mbstring, zip
          tools: prestissimo

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Coding Style Checks
        run: composer test:lint

      - name: Type Checks
        run: composer test:types
